### ISSUE TITLE
Explore: Remove Alternative Codecs in favor of Public "Jump Instruction" function

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#225]
# Description
- Alternative codecs have marginal gas improvements, but they have not been fully optimized, making them marginally beneficial.
- Gut feeling is that the design to get the alternative codecs working adds more gas cost than it saves in the high probability scenarios (one-off actions, or two bundled instructions).
- Jump instruction is really powerful, but its gated by a complex mechanism to use it
- This potentially reduces a lot of the contract's size described in here: https://github.com/primitivefinance/hyper/issues/209

# Tasks
- [ ] Measure gas of each internal function, the gas of the public function wrappers, and the gas of the processing logic.
- [ ] Explore the benefits with respect to swap the most. Swaps are very important, so they should get the optimization.
- [ ] Explore a public function that will process encoded calldata. Only difference is that the function signature is 4 bytes instead of the jump instruction code.
